### ISSUE TITLE
Error: No signatures found matching the expected signature for payload

### ISSUE THREAD

**Issue by crimsondeal** [GaryH21/Stripe-Webhooks-Tutorial#1]
Receiving via firebase functions logs:

> Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing

Using the code verbatim-- any thoughts? Have tried:

`let event = stripe.webhooks.constructEvent(request.body, sig, endpointSecret);`

and

`let event = stripe.webhooks.constructEvent(request.rawBody, sig, endpointSecret);`

**Comment by GaryH21** [comment]
Hmm, interesting. Have you set up your secrets in Firebase?

I have a guide here that walks through this code, not sure if you have seen:
https://medium.com/@GaryHarrower/working-with-stripe-webhooks-firebase-cloud-functions-5366c206c6c

**Comment by crimsondeal** [comment]
Ugh, I’m a fool! Was using the live secret key for sending test webhooks, thus it was resulting in this error.

After adjusting this, I started getting the following error:

> TypeError: Key must be a buffer at new Hmac (crypto.js:117:16) at Object.createHmac (crypto.js:643:10)

Using the following ended up fixing it for me:

`let event = stripe.webhooks.constructEvent(request.rawBody, sig, Buffer.from(endpointSecret)); `

Thank you for a great tutorial and code-- this was perfect for what I needed!

**Comment by GaryH21** [comment]
Great, glad you got it sorted and happy the tutorial was useful! 🙂
